name: "Feature request"
description: Suggest a new feature or improvement
labels: ["feature", "triage-needed"]

body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checks
      options:
        - label: I searched existing issues and didn't find a match.
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the feature or improvement you are requesting.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Explain why this feature would be useful and what problem it would solve.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Possible implementation
      description: (Optional) Suggest how this feature could be implemented, if you have ideas.
